### ISSUE TITLE
MVP Features as per Project Assignment

### ISSUE THREAD

**Issue by GillianTrethewey** [chingu-voyages/v44-tier2-team-26#20]
**__Feature Description__**
Overall Project Scope

**__Major User Stories/tasks__**

**__Initial Configuration__**
- [x] #36

**__Basic Configuration__**
- [x] #34
- [x] #35
- [x] #37
- [x] #38
- [x] #39
- [x] #40

**__Display Components__**
- [x] #33
- [x] #28
- [x] #29
- [x] #30
- [x] #31
- [x] #32

**__Time for Research__**

**__Logic Components__**

**__Further Movement Logic__**

**__Additional Considerations__**
Think about how each of these can be divided up between team members. They are roughly in order.

**Comment by egoullaud** [comment]
Hey! Here are some notes from Jim's Talk today about how these Issues work! 

We are using User Story where we should be using "Task" ?

Here's a quick rundown of what he said on the call:

Epic: Broad statement of functionality 
- Each feature typically gets an epic that then has tasks and user stories assigned under it for each sprint

User Story: Description of user requirements in user terminology (He also said this isn't important for our use case this voyage since we don't have "end users")
- User stories describe the bits of the feature in terms of what the user wants to do and ends with a value state from the user.

Task: The granular technical units of work
-this is what gets assigned out to team members. 


My suggestion moving forward: 
1. Create epics for each feature
2. write a description in the epic with the user story
3. tasks for each sprint that get assigned out
